version: '3'

services:
  app:
    image: node:15
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - './node/:/usr/src/app'
    ports:
      - '3001:3001'
    command: node app.js
